"""create product and user tables

Revision ID: 11a0586e1cef
Revises:
Create Date: 2025-10-29 19:07:20.899837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11a0586e1cef"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "description", sa.String(), nullable=False
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column(
            "discounPrice", sa.Integer(), nullable=False
        ),
        sa.Column(
            "discount", sa.Integer(), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_id"),
        "product",
        ["id"],
        unique=True,
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        op.f("ix_user_id"), "user", ["id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(
        op.f("ix_product_id"), table_name="product"
    )
    op.drop_table("product")
    # ### end Alembic commands ###
