import type { Metadata } from 'next';
import { Bricolage_Grotesque } from 'next/font/google';
import './globals.css';

const BricolageGrotesque = Bricolage_Grotesque({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    default: 'Clothing Store',
    template: '%s | Clothing Store',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${BricolageGrotesque.className}  antialiased`}>
        {children}
      </body>
    </html>
  );
}
